get_mort <- function(mort){ 
    #' Extracts mortality counts for selected age categories.
    #'
    #' @description This function inputs mortality data generated by
    #' html script from the Central Statistics Office.  It removes extraneous
    #' columns and rows.  Then it extracts the following age categories:
    #' "0 to 4", "5 to 14", "15 to 24", "25 to 34", 
    #' "35 to 44", "45 to 54", "55 to 64", "65 to 74", 
    #' "75 and Over"
    #' The input data records quarter years.  These are aggregated to
    #' yearly totals.  
    #' 
    #' @param mort data table. There are 810 observations of mortality
    #' by age category, from 2010Q1 to 2023Q2.  Rows are sorted by year quarter
    #' descending
    #' @usage get_mort(mort)
    #' @return A data table one column for the CSO age categories and 
    #' the other giving the mortality counts.  There are 11 observations with 
    #' age groupings up to age 74 and a single observation for 75 years
    #'  and over
    
    # Remove unused columns
    mort[, c("statistic", "unit") := NULL]
    setnames(mort, "value", "count")
    
    # Convert "count" column from char to integer
    # First, remove commas
    mort[, count := str_remove_all(count, ",")]
    # Second, replace missing values with 0
    mort[count == "..", count := "0"]
    # Third, convert to numeric
    mort[, count := as.numeric(count)]

    # Extract relevant age categories
    mort <- mort[age_at_death %in% 
                c("Under 1 Year", "1 to 4 Years", "5 to 14 Years", 
                  "15 to 24 Years", "25 to 34 Years", "35 to 44 Years",
                  "45 to 54 Years", "55 to 64 Years", "65 to 74 Years",
                  "75 Years and Over"), ]

    # Convert quarters to years
    yr_23_20 <- str_sub(mort$quarter, 1, 4)
    mort[, year := yr_23_20][, quarter := NULL]
    # Convert "year" column to numeric
    mort[, year := as.numeric(year)]
    
    # Convert "age_at_death" to single age
    age_start <- str_sub(mort$age_at_death, 1, 2)
    # Deal with "Under 1 year" group
    age_char <- str_replace_all(age_start, "Un", "0")
    age_yr <- as.numeric(age_char)
    mort[, age := age_yr][, age_at_death := NULL]   
    
    # aggregate "count" for each year
    mort[, count := sum(count), by = c("year", "age")]
    
    # Remove duplicate rows
    mort <- dplyr::distinct(mort)
    
    # combine age groups 0 and 1
    mort[age %in% 0:1, count:=sum(count), by = year]
    # remove age 1 since it has been combined with age 0
    mort <- mort[age != 1, ]
    
    # Convert age to a factor
    mort[, age := as.factor(age)]
    # Relabel factors to age range
    mort[, age_cat := plyr::mapvalues(mort$age, 
            from = c("0", "5", "15","25", "35", "45", "55", "65", "75"), 
            to = c("0-4", "5-14", "15-24","25-34", "35-44", "45-54", 
                   "55-64", "65-74", "75+")) 
    ][, age := NULL]
    
    # Calculate yearly total deaths
    total_yr <- mort[, sum(count), by = year][, Total := V1][, V1 := NULL]
    # Create data table for total counts
    total_df <- data.frame(count = total_yr$Total, 
                           year = 2023:2010, 
                           age_cat = as.factor("Total"))
    # for each year, there are 9 age categories
    # insert total counts every 9 rows
    mort_all <- rbind(mort[1:9, ], total_df[1,],
          mort[10:18, ], total_df[2,],
          mort[19:27, ], total_df[3,],
          mort[28:36, ], total_df[4,],
          mort[37:45, ], total_df[5,],
          mort[46:54, ], total_df[6,],
          mort[55:63, ], total_df[7,],
          mort[64:72, ], total_df[8,],
          mort[73:81, ], total_df[9,],
          mort[82:90, ], total_df[10,],
          mort[91:99, ], total_df[11,],
          mort[100:108, ], total_df[12,],
          mort[109:117, ], total_df[13,],
          mort[118:126, ], total_df[14,]
          )
    
    return(mort_all)
}