get_census <- function(pop){ 
    #' Convert population counts by year of age to 5-year age
    #' categories up to the 80 years and over group.
    #'
    #' @description This function inputs the csv file generated by
    #' html script from the Central Statistics Office.  It removes extraneous
    #' columns and rows.  Then it aggregates single year counts into
    #' 5-year age categories.  Halts execution if total count recorded in source data 
    #' does not equal sum of age categories
    #'
    #' 
    #' @param pop data table. There are 102 rows.  Observations are 
    #' for ages 0 to 100 along with one for "All ages".  The 2016 data
    #' contains additional observations for "Under 15 years" and 
    #' "15 years and over"
    #' @usage get_census(pop)
    #' @return A data table one column for the 5-year age category and the other
    #' giving the population count.  There are 17 observations with 
    #' 5-year groupings up to age 79 and a single observation for 80 years
    #'  and over

    # Census for 2022 and 2016 give different names to columns
    if ("Single Year of Age" %in% colnames(pop)){
        # Census year is 2022 or 2011
        setnames(pop, "Single Year of Age", "age")
        pop[, "CensusYear" := NULL]
        if("County and City" %in% colnames(pop)) {
            pop[, "County and City" := NULL]
        }
    } else if ("Yearly Age" %in% colnames(pop)){
        # Census year is 2016
        setnames(pop, "Yearly Age", "age")
        pop[, c("Year", "Marital Status") := NULL]
        # Remove rows for "Under 15 years" and "15 years and over"
        pop <- pop[!(age %in% c("Under 15 years", "15 years and over")), ]
        
    }
    
    # Remove unused columns
    pop[, c("Statistic", "Sex", "Unit") := NULL]
    setnames(pop, "Value", "count")
    
    # Convert count column to integer
    # First, remove commas
    pop[, count := str_remove_all(count, ",")]
    pop[, count := as.numeric(count)]
    
    # Extract total population count
    total <- pop[age == "All ages", count]
    # Remove observation for "All ages"
    pop <- pop[age != "All ages", ]
    
    # Combine ages >= 80 into one group "80+"
    over80 <- pop[81:101, sum(count)]
    # remove rows for 80 and over
    pop <- pop[1:80, ]
    
    # Use integers to represent year of age
    pop[, age := 0:79]
    
    # Aggregate pop counts into 5-year age categories
    pop[, age_cat := cut2(age, g = 16)]
    
    # sum the pop numbers in each age category
    pop_cats <- pop[, sum(count), by = age_cat]
    pop_cats[, count := V1][, V1 := NULL]
    
    # append an entry for the 90 plus group
    oldest <- data.table(age_cat = "80+", 
                         count = over80)
    pop <- rbind(pop_cats, oldest)
    
    # update "age_cat" for compatibility with other years
    age_5yr_cat <- c("0-4", "5-9", "10-14", "15-19", "20-24", 
                     "25-29", "30-34", "35-39", "40-44", "45-49", 
                     "50-54", "55-59", "60-64", "65-69", "70-74", "75-79",
                     "80+")
    pop[, age_cat := age_5yr_cat]
    
    # Check that pop total equals 
    # sum of pop in age categories
    verify(pop, total == pop[, sum(count)],
           success_fun = success_logical )
    return(pop)
}