get_mort_qtr <- function(mort){ 
    #' Extracts mortality counts for selected age categories.
    #'
    #' @description This function inputs mortality data generated by
    #' html script from the Central Statistics Office.  It removes extraneous
    #' columns and rows.  Then it extracts the following age categories:
    #' "0 to 4", "5 to 14", "15 to 24", "25 to 34", 
    #' "35 to 44", "45 to 54", "55 to 64", "65 to 74", 
    #' "75 and Over"
    #' The input data records quarter years.  
    #' 
    #' @param mort data table. There are 810 observations of mortality
    #' by age category, from 2010Q1 to 2023Q2.  Rows are sorted by year quarter
    #' descending
    #' @usage get_mort(mort)
    #' @return total_qtr data table: 
    #'     quarter: year and quarter 
    #'     count: number of deaths in yearly quarter
    
    # Remove unused columns
    mort[, c("statistic", "unit") := NULL]
    #setnames(mort, "value", "count")
    
    # Convert "count" column from char to integer
    # First, remove commas
    mort[, count := str_remove_all(count, ",")]
    # Second, replace missing values with 0
    mort[count == "..", count := "0"]
    # Third, convert to numeric
    mort[, count := as.numeric(count)]

    # Extract relevant age categories
    mort <- mort[age_at_death %in% 
                c("Under 1 Year", "1 to 4 Years", "5 to 14 Years", 
                  "15 to 24 Years", "25 to 34 Years", "35 to 44 Years",
                  "45 to 54 Years", "55 to 64 Years", "65 to 74 Years",
                  "75 Years and Over"), ]

    # Convert "age_at_death" to single age
    age_start <- str_sub(mort$age_at_death, 1, 2)
    # Deal with "Under 1 year" group
    age_char <- str_replace_all(age_start, "Un", "0")
    age_yr <- as.numeric(age_char)
    mort[, age := age_yr][, age_at_death := NULL]   
    
    # Convert age to a factor
    mort[, age := as.factor(age)]
    # Relabel factors to age range
    mort[, age_cat := plyr::mapvalues(mort$age, 
            from = c("0", "1", "5", "15","25", "35", "45", "55", "65", "75"), 
            to = c("0","1-4", "5-14", "15-24","25-34", "35-44", "45-54", 
                   "55-64", "65-74", "75+")) 
    ][, age := NULL]
    
    # Calculate quarter total deaths
    total_qtr <- mort[, sum(count), by = quarter][, Total := V1][, V1 := NULL]
    
    return(total_qtr)
}